//! Rendering `packages/test-utils/src/fixtures.ts`.

use base64::prelude::*;
use miden_client::account::Account;
use miden_client::note::Note;
use miden_client::utils::Serializable;

/// Everything the generated file is written from.
pub struct Fixtures {
    /// The network the accounts and notes were deployed to, for the header.
    pub network_id: String,
    pub counter_contracts: [Account; 2],
    pub count_reader: Account,
    pub basic_wallet: Account,
    pub counter_notes: [Note; 2],
}

impl Fixtures {
    /// Renders the file.
    ///
    /// The layout is biome's own — 2-space indent, 80-column width, double
    /// quotes — reproduced here so that a freshly generated file is already
    /// formatted: the `resource` blobs and the note ids overflow the line and so
    /// sit on a continuation line, while the shorter account ids do not.
    pub fn render(&self) -> String {
        let mut out = String::new();

        out.push_str(&format!(
            "// Generated by apps/api-compile/crates/generate-fixtures against {}.\n",
            self.network_id
        ));
        out.push_str("// Do not edit by hand — regenerate with `pnpm generate-fixtures`.\n\n");

        for (index, account) in self.counter_contracts.iter().enumerate() {
            out.push_str(&format!(
                "export const COUNTER_CONTRACT_ID_{} = \"{}\";\n",
                index + 1,
                account.id().to_hex()
            ));
        }
        out.push_str(&format!(
            "export const COUNT_READER_ID = \"{}\";\n",
            self.count_reader.id().to_hex()
        ));
        out.push_str(&format!(
            "export const BASIC_WALLET_ID_1 = \"{}\";\n\n",
            self.basic_wallet.id().to_hex()
        ));

        // Only the accounts a test hands to the verifier as a local blob need an
        // entry; `COUNTER_CONTRACT_ID_2` is only ever looked up on-chain.
        out.push_str("export const accounts = {\n");
        out.push_str(&account_entry(
            "COUNTER_CONTRACT_ID_1",
            &self.counter_contracts[0],
        ));
        out.push_str(&account_entry("COUNT_READER_ID", &self.count_reader));
        out.push_str(&account_entry("BASIC_WALLET_ID_1", &self.basic_wallet));
        out.push_str("};\n\n");

        for (index, note) in self.counter_notes.iter().enumerate() {
            out.push_str(&format!(
                "export const COUNTER_NOTE_ID_{} =\n  \"{}\";\n",
                index + 1,
                note.id().to_hex()
            ));
        }
        out.push('\n');

        out.push_str("export const notes = {\n");
        out.push_str(&note_entry("COUNTER_NOTE_ID_1", &self.counter_notes[0]));
        out.push_str("};\n");

        out
    }
}

/// One `accounts` entry. `resource` is what `miden-verifier --resource-path`
/// reads back with `Account::read_from_bytes`, and `code` is the commitment
/// `miden-import` reports for the same account.
fn account_entry(key: &str, account: &Account) -> String {
    entry(
        key,
        &BASE64_STANDARD.encode(account.to_bytes()),
        &account.code().commitment().to_hex(),
    )
}

/// One `notes` entry — the note equivalent of [`account_entry`], keyed on the
/// note script's root rather than an account code commitment.
fn note_entry(key: &str, note: &Note) -> String {
    entry(
        key,
        &BASE64_STANDARD.encode(note.to_bytes()),
        &note.script().root().to_hex(),
    )
}

fn entry(key: &str, resource: &str, code: &str) -> String {
    format!("  [{key}]: {{\n    resource:\n      \"{resource}\",\n    code: \"{code}\",\n  }},\n")
}
